"""make_subject_nullable

Revision ID: 4270d30c093e
Revises: e128dd2d4b80
Create Date: 2026-03-05 00:18:24.591169
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '4270d30c093e'
down_revision: Union[str, None] = 'e128dd2d4b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default="general")

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default="general")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default=None)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default=None)
    # ### end Alembic commands ###
